#!/bin/bash

# Function to display usage instructions
usage() {
    echo "Usage: $0 -p <port> -d <directory> [-n <name>] [-q] [-h]"
    echo "    -p  Specify the port to expose (default: 8080)"
    echo "    -d  Specify the directory to mount into the container"
    echo "    -n  Specify the container name (default: dockerdown)"
    echo "    -q  Enable quiet mode (optional)"
    echo "    -h  Display this help message"
    exit ${1:-1}  # Exit with provided status code or 1 if not provided
}

# Default values
PORT=8080
DIRECTORY=""
NAME="dockerdown"
QUIET="false"

# Parse command-line arguments
while getopts "p:d:n:qh" opt; do
    case "${opt}" in
        p)
            PORT=${OPTARG}
            ;;
        d)
            DIRECTORY=${OPTARG}
            ;;
        n)
            NAME=${OPTARG}
            ;;
        q)
            QUIET="true"
            ;;
        h)
            usage 0  # Exit with status code 0 for help
            ;;
        *)
            usage 1  # Exit with status code 1 for errors
            ;;
    esac
done

# Check if directory is provided and exists
if [ -z "${DIRECTORY}" ]; then
    echo "Error: Directory not specified."
    usage 1
elif [ ! -d "${DIRECTORY}" ]; then
    echo "Error: Directory '${DIRECTORY}' does not exist."
    exit 1
fi

# Display messages if not in quiet mode
if [ "${QUIET}" != "true" ]; then
  echo "Starting Docker container '${NAME}' on port ${PORT} with directory ${DIRECTORY}..."
  docker run --rm --name ${NAME} -p ${PORT}:80 -v "${DIRECTORY}:/usr/local/nginx/html/files" lphxl/dockerdown:latest
else
  echo "Running in quiet mode."
  docker run -d --rm --name ${NAME} -p ${PORT}:80 -v "${DIRECTORY}:/usr/local/nginx/html/files" lphxl/dockerdown:latest
fi 